### ISSUE TITLE
Incompatible debian version

### ISSUE THREAD

**Issue by X-Ryl669** [darylounet/libnginx-mod-brotli#1]
Currently, the debian Buster version of nginx is 1.14.2 yet the module you have built are targeting nginx 1.18.0. How do you sort this out ?

**Comment by darylounet** [comment]
Hi,
> Currently, the debian Buster version of nginx is 1.14.2 yet the module you have built are targeting nginx 1.18.0. How do you sort this out ?

My repository is only compatible with the official stable & mainline NGiNX repository for Debian / Ubuntu.
You can replace your 1.14 NGiNX with the official 1.18 one then use my repository to install mod-brotli. To do this you can follow the official instructions : https://nginx.org/en/linux_packages.html#Debian
