### ISSUE TITLE
Does not work?

### ISSUE THREAD

**Issue by dgilman** [darylounet/libnginx-mod-brotli#2]
Packages are all getting built against / having dependencies against the latest nginx in debian, 1.18, for all Debian distros. For example right now this repo isn't usable against debian stable as it only ships nginx 1.14.

**Comment by darylounet** [comment]
This repository is not intended to be used with distribution packages. You have to use it with the official NGiNX repository :
https://nginx.org/en/linux_packages.html#Debian
But it's true that it is noted nowhere, I should add it in the README.
