### ISSUE TITLE
nginx 1.24.0 released

### ISSUE THREAD

**Issue by abcfy2** [darylounet/libnginx-mod-brotli#5]
Please upgrade this package to support this new version. Thanks.

Or you can set up github action [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) jobs to automate publish the new version.

Thanks.

**Comment by darylounet** [comment]
Hi @abcfy2 ! It's now [released](https://github.com/darylounet/libnginx-mod-brotli/releases/tag/brotli-1.0.9%2Fnginx-1.24.0-1) !
Thanks for your advice, I've already planned to automate through [push trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push) on [nginx git mirror](https://github.com/nginx/nginx/tags), but I don't have enough time for the moment.
